name: pipeline
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        dependencies: ['lowest', 'highest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: "none"

      - name: Composer Validation
        run: composer validate --strict

      - name: Install Composer
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Install PHP Dependencies
        run: composer install --no-scripts

      - name: Tests
        run: vendor/bin/phpunit --exclude-group inspector

  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: "none"

      - name: Composer Validation
        run: composer validate --strict

      - name: Install Composer
        uses: "ramsey/composer-install@v3"

      - name: Install PHP Dependencies
        run: composer install --no-scripts

      - name: Code Style PHP
        run: vendor/bin/php-cs-fixer fix --dry-run

      - name: PHPStan
        run: vendor/bin/phpstan analyse
